# Generated by Django 4.2.1 on 2023-05-16 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Date when deleted', null=True, verbose_name='Deleted At')),
                ('delete_reason', models.CharField(blank=True, default=None, help_text='Delete Reason', max_length=300, null=True, verbose_name='Delete Reason')),
                ('name', models.CharField(help_text='File name', max_length=255, verbose_name='File name')),
                ('url', models.TextField(blank=True, help_text='File URL', null=True, verbose_name='File URL')),
            ],
            options={
                'verbose_name': 'Chatbot File',
                'verbose_name_plural': 'Chatbot Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Date when deleted', null=True, verbose_name='Deleted At')),
                ('delete_reason', models.CharField(blank=True, default=None, help_text='Delete Reason', max_length=300, null=True, verbose_name='Delete Reason')),
                ('name', models.CharField(help_text='Chatbot name', max_length=128, verbose_name='Chatbot name')),
                ('description', models.TextField(blank=True, help_text='Chatbot Description', null=True, verbose_name='Chatbot Description')),
                ('category', models.CharField(choices=[('1', 'Text'), ('2', 'CSV')], default='1', help_text='Chatbot category', max_length=11, verbose_name='Chatbot category')),
                ('base_prompt', models.TextField(blank=True, help_text='Chatbot base prompt', null=True, verbose_name='Chatbot base prompt')),
                ('model', models.CharField(choices=[('1', 'gpt-3.5-turbo')], default='1', help_text='Chatbot model', max_length=11, verbose_name='Chatbot model')),
                ('file_urls', models.ManyToManyField(blank=True, help_text='Chatbot file urls', related_name='chatbot_file_urls', to='chatbot.chatbotfile', verbose_name='Chatbot file urls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
                'ordering': ['-created_at'],
            },
        ),
    ]
