# Generated by Django 4.2.1 on 2023-05-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='question_limit',
            field=models.IntegerField(default=0, help_text='Question limit', verbose_name='Question limit'),
        ),
    ]
