# Generated by Django 4.2.1 on 2023-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbot_question_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='open_ai_key',
            field=models.CharField(default='', help_text='Open ai key', max_length=255, verbose_name='Open ai key'),
        ),
    ]
