# Generated by Django 4.2.1 on 2023-05-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatbot_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Date when deleted', null=True, verbose_name='Deleted At')),
                ('delete_reason', models.CharField(blank=True, default=None, help_text='Delete Reason', max_length=300, null=True, verbose_name='Delete Reason')),
                ('fingerprint', models.CharField(help_text='Device Fingerprint', max_length=255, verbose_name='Device Fingerprint')),
            ],
            options={
                'verbose_name': 'Chatbot devices',
                'verbose_name_plural': 'Chatbot devices',
                'ordering': ['-created_at'],
            },
        ),
    ]
