# Generated by Django 4.2.1 on 2023-05-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatbotdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='open_ai_key',
            field=models.CharField(blank=True, default='', help_text='Open ai key', max_length=255, null=True, verbose_name='Open ai key'),
        ),
    ]
