# Generated by Django 4.2.1 on 2023-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_chatbot_open_ai_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotdevice',
            name='question_limit',
            field=models.IntegerField(default=0, help_text='Question limit', verbose_name='Question limit'),
        ),
    ]
