# Generated by Django 4.2.1 on 2023-05-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chatbotdevice_question_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotdevice',
            name='chatbot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot', to='chatbot.chatbot'),
        ),
    ]
