# Generated by Django 4.2.1 on 2023-05-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chatbotdevice_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='bot_logo',
            field=models.ForeignKey(blank=True, help_text='Chatbot logo url', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_logo_url', to='chatbot.chatbotfile', verbose_name='Chatbot logo url'),
        ),
    ]
