# Generated by Django 4.2.1 on 2023-05-22 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_chatbot_bot_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='chatbotdevice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Uuid'),
        ),
        migrations.AddField(
            model_name='chatbotfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Uuid'),
        ),
    ]
