# Generated by Django 4.2.1 on 2023-05-23 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chatbot_uuid_chatbotdevice_uuid_chatbotfile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='align_chat_button',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Align chat button', max_length=11, verbose_name='Align chat button'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='auto_open_chat_window_after',
            field=models.IntegerField(default=2, help_text='Auto open chat window after', verbose_name='Auto open chat window after'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='button_color',
            field=models.CharField(blank=True, default='#000000', help_text='Chat button color', max_length=28, null=True, verbose_name='Chat button color'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='chat_icon',
            field=models.ForeignKey(blank=True, help_text='Chat icon url', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_icon_url', to='chatbot.chatbotfile', verbose_name='Chat icon url'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Display bot name', max_length=128, null=True, verbose_name='Display bot name'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Bot theme', max_length=11, verbose_name='Bot theme'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='user_message_color',
            field=models.CharField(blank=True, default='#3B81F6', help_text='User message color', max_length=28, null=True, verbose_name='User message color'),
        ),
    ]
