# Generated by Django 4.2.1 on 2023-05-23 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_chatbot_align_chat_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, verbose_name='Uuid'),
        ),
        migrations.AlterField(
            model_name='chatbotdevice',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, verbose_name='Uuid'),
        ),
        migrations.AlterField(
            model_name='chatbotfile',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, verbose_name='Uuid'),
        ),
    ]
