# Generated by Django 4.2.1 on 2023-05-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_alter_chatbot_uuid_alter_chatbotdevice_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='domains',
            field=models.TextField(blank=True, help_text='Chatbot allowed domains', null=True, verbose_name='Chatbot allowed domains'),
        ),
    ]
