# Generated by Django 4.2.1 on 2024-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_chatbot_base_prompt_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
