# Generated by Django 4.2.1 on 2023-06-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docchatbotfile',
            name='num_of_characters',
            field=models.IntegerField(default=0, help_text='Number of characters', verbose_name='Number of characters'),
        ),
    ]
