# Generated by Django 4.2.1 on 2023-07-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgpt', '0002_docchatbotfile_num_of_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='docchatbot',
            name='base_prompt_message',
            field=models.TextField(blank=True, help_text='Chatbot base prompt message', null=True, verbose_name='Chatbot base prompt message'),
        ),
        migrations.AddField(
            model_name='docchatbot',
            name='second_base_prompt_message',
            field=models.TextField(blank=True, help_text='Chatbot second base prompt message', null=True, verbose_name='Chatbot second base prompt message'),
        ),
    ]
